fix: navbar styled 수정
TEO-SPRINT-14th-9team/mz2mo-client pull request #19
Opened 2023-02-26 17:47 UTC by moomiz

## Issue Number
 #3 
## Epic
 navbar styled 수정 했습니다. 
## Description
*컨벤션에 맞지 않았던 styled 수정했습니다.
## Checklist

- [ ] Code Review 요청
- [ ] PR 제목 commit convention에 맞는지 확인
- [ ] Label 설정

2023-02-26 17:56 UTC, haryung-lee requested changes

2023-02-26 17:56 UTC, haryung-lee commented on src/components/common/navigation/navigation.tsx
> +            <style.MenuText>가입하기</style.MenuText>
a 태그 쓸 때 next/link에서 제공하는 Link태그로 한번 감싸주면 좋을것 같아요~

2023-02-26 17:56 UTC, haryung-lee commented on src/components/common/navigation/navigation.tsx
> +            <style.MenuText>|</style.MenuText>
요거는 나누는 divider 역할인것 같아서 MenuText (a태그) 말고 따로 정의해줘도 좋을것 같아요!

2023-02-26 17:56 UTC, haryung-lee commented on src/components/layout/headerLayout.tsx
> +    <div>
여기 div 태그 말고 그냥 빈 태그로 줘도 좋을거 같네요!

<></> 요렇게요!

2023-02-26 17:57 UTC, haryung-lee commented on src/components/common/navigation/navigation.tsx
> +            <style.MenuText>가입하기</style.MenuText>
대충 검색하면 나오는 내용일텐데 아래 내용 한번 보실래요??

Next.js는 React를 기반으로 한 프레임워크로, SPA(Single Page Application)에서 발생하는 SEO(Search Engine Optimization) 문제와 초기 로딩 시간 등의 문제를 보완하여 좀 더 나은 사용자 경험(UX)을 제공합니다.

next/link는 Next.js에서 제공하는 링크 컴포넌트로, React Router와 비슷한 역할을 합니다. 하지만, React Router는 클라이언트 사이드 라우팅을 기반으로 동작하는 반면, Next.js의 next/link 컴포넌트는 서버 사이드 렌더링(SSR)을 지원합니다.

next/link를 사용하면 페이지 전환 시 클라이언트 사이드 라우팅으로 인한 페이지 새로고침이 발생하지 않고, 서버 사이드 렌더링을 지원하여 초기 로딩 시간을 단축할 수 있습니다. 또한, next/link는 브라우저의 캐시를 이용하여 이전에 방문한 페이지를 더 빠르게 로드할 수 있도록 지원합니다.

또한, next/link는 href 속성 대신 as 속성을 사용하여 가독성이 높은 URL을 제공할 수 있습니다. 이렇게 제공된 URL은 검색 엔진 최적화(SEO)에도 도움이 됩니다.

따라서, Next.js를 사용하는 경우 next/link를 사용하여 클라이언트 사이드 라우팅 대신 서버 사이드 렌더링을 지원하고, 초기 로딩 시간을 단축하여 사용자 경험을 향상시킬 수 있습니다.

2023-02-27 01:21 UTC, moomiz commented on src/components/common/navigation/navigation.tsx
> +            <style.MenuText>가입하기</style.MenuText>
하랭 친절한 설명 너무 감사해요!

2023-03-11 09:58 UTC, closed without merging